name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Java 21
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          cache: gradle

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: build/libs/